header-from: ./.config/header.md

version: ""

formatter: markdown table

name: terraform-aws-iam-group-with-user-self-service

content: |-
  {{ .Header }}

  # terraform-aws-iam-group-with-user-self-service

  GitHub: [StratusGrid/terraform-aws-iam-group-with-user-self-service](https://github.com/StratusGrid/terraform-aws-iam-group-with-user-self-service)

  This module is used to create an IAM group which has user self service permissions.
  
  <span style="color:red">NOTE:</span> When in AWS console, the user must access their security credentials by the username dropdown in the top right > 'My Security Credentials'
  
  ## Example usage of the module:
  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  ---

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - header
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace